os: linux
dist: bionic
language: python
python:
  - '3.6'
  - '3.7'
git:
  depth: false
cache: pip
before_install:
  - pip install pipenv
install:
  - pipenv sync
script:
  - lsb_release -a
  - pip list
  - python -m pytest
  - python -m umldotcs -o tests_sln.gv ./tests/sln/
jobs:
  include:
    - stage: analysis
      if: branch = master
      before_install:
        - pip install codecov
        - pip install pipenv
      install:
        - pipenv sync
        - pipenv install pytest_cov # argh!
        - pipenv install 'black==19.10b0'
      addons:
        sonarcloud:
          organization: kthy
      script:
        - pipenv run black_ci
        - python -m pytest --cov-branch --cov-report term-missing:skip-covered --cov-report xml --cov=umldotcs tests/
      after_success:
        - codecov
        - sonar-scanner
